{% set name = "dagster_ge" %}
{% set version = "0.6.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("_", "-") }}-{{ version }}.tar.gz"
  sha256: 3d0ca69a89648d63b59c6e1c42d0bb534752114121ad795d4e95e1d7b5724f4f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}.*
    - great-expectations <=0.7.6

test:
  imports:
    - dagster_ge

about:
  home: "https://github.com/dagster-io/dagster"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Great Expectations plugin for Dagster"

extra:
  recipe-maintainers:
    - conda-forge/dagster
