{% set name = "dagster_ge" %}
{% set version = "0.6.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("_", "-") }}-{{ version }}.tar.gz"
  sha256: 5c35d1751c5bcacf452147156c60695b4813042cb82b892f88e217e3fe8af659

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}.*
    - enum-compat >=0.0.1
    - future >=0.16.0
    - great-expectations <=0.7.6

test:
  imports:
    - dagster_ge

about:
  home: "https://github.com/dagster-io/dagster"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Great Expectations plugin for Dagster"

extra:
  recipe-maintainers:
    - xhochy
